[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in these schemas will get API endpoints.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

[functions.make-server-aa1c64f0]
verify_jwt = false

